#!/bin/bash
#$ -l mem_free=6G
#$ -l h_vmem=6G
#$ -l h_rt=24:00:00
#$ -cwd
#$ -j y
#$ -R y
#$ -t 1-1000

mkdir -p results
if [ ! -f "/results/run-$SGE_TASK_ID" ]; then
  Rscript doSimParal.R $SGE_TASK_ID 1000 5 .75 1 20 1000
fi